openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
    description: Production Environment
  - url: http://localhost:44424/test-api/v1
    description: Localhost Environment
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
  /name:
    get:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
components:
  schemas:
    Production:
      type: object
      properties:
        id:
          type: string
          description: "Product ident"
         